language: cpp

compiler:
  - clang
  - gcc

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libzmq3-dev libboost-all-dev

before_script:
  - mkdir build
  - cd build

script: cmake -D Remus_NO_SYSTEM_BOOST:BOOL=OFF .. && make

notifications:
  email:
    - robert.maynard@kitware.com
  on_success: change
  on_failure: always