language: cpp

compiler:
  - clang
  - gcc
env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release

before_install:
  - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
  - echo "yes" | sudo add-apt-repository ppa:mapnik/boost
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get purge libboost*1.46*
  - sudo apt-cache policy libboost-dev
  - sudo apt-get install -qq libboost-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev
  - sudo apt-get install -qq libzmq3-dev
  - sudo apt-get install curl

script:
  - git branch travis
  - git checkout travis
  - mkdir build
  - ctest -S travis.cmake -VV || true

after_success:
  - curl http://cbadges.com/Remus/pullRequest/robertmaynard/Remus/${TRAVIS_PULL_REQUEST}/${TRAVIS_COMMIT}

notifications:
  email:
    - robert.maynard@kitware.com
  on_success: change
  on_failure: always
