language: cpp

compiler:
  - clang
  - gcc
env:
  - BUILD_CONFIG=Debug
  - BUILD_CONFIG=Release

before_install:
   # Add PPA for recent boost libraries
  - sudo add-apt-repository --yes ppa:boost-latest/ppa
  - sudo add-apt-repository --yes ppa:dcthomp/smtk
   # Make sure package index is up to date:
  - sudo apt-get update -qq

install:
  # Remove cmake-data package as it interferes with SMTK PPA cmake package:
  - sudo dpkg -r cmake cmake-data
  - sudo apt-get install -yqq cmake
  - sudo apt-get install -yqq libboost1.54-dev libboost-filesystem1.54-dev libboost-system1.54-dev libboost-thread1.54-dev
  - sudo apt-get install -yqq libzmq3-dev
  - sudo apt-get install curl

script:
  - git branch travis
  - git checkout travis
  - mkdir build
  - ctest -S travis.cmake -V

notifications:
  email:
    - robert.maynard@kitware.com
  on_success: change
  on_failure: always
